### ISSUE TITLE
Editing the job board page causes an Internal Server Error

### ISSUE THREAD

**Issue by malemburg** [python/pythondotorg#317]
I'm trying to remove an entry from the job board page (https://www.python.org/admin/pages/page/57/), but keep getting an Internal Server Error message when trying to save the edit, with no further details.

Here's the HTML - perhaps the formatting hints at the origin of the error:

```
 <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1>Internal Server Error</h1>

  </body>
 </html>
```

**Comment by fcurella** [comment]
From the traceback I've received, seems to be related to the ReST context of the `admindocs`:

```
Traceback (most recent call last):

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admin/options.py", line 1105, in change_view
    self.save_model(request, new_object, form, True)

  File "/srv/redesign.python.org/releases/fd8fb7741bb4544f18a3fc36d4f79094aaa94b73/cms/admin.py", line 18, in save_model
    return super().save_model(request, obj, form, change)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admin/options.py", line 740, in save_model
    obj.save()

  File "/srv/redesign.python.org/releases/fd8fb7741bb4544f18a3fc36d4f79094aaa94b73/cms/models.py", line 35, in save
    return super().save(**kwargs)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/db/models/base.py", line 624, in save_base
    values = [(f, None, (raw and getattr(self, f.attname) or f.pre_save(self, False))) for f in non_pks]

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/db/models/base.py", line 624, in <listcomp>
    values = [(f, None, (raw and getattr(self, f.attname) or f.pre_save(self, False))) for f in non_pks]

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/markupfield/fields.py", line 140, in pre_save
    rendered = self.markup_choices_dict[value.markup_type](raw)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/markupfield/markup.py", line 74, in render_rest
    settings_overrides=overrides)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/core.py", line 448, in publish_parts
    enable_exit_status=enable_exit_status)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/core.py", line 217, in publish
    self.settings)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 383, in new_subsection
    textnodes, title_messages = self.inline_text(title, lineno)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 427, in inline_text
    return self.inliner.parse(text, lineno, self.memo, self.parent)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 513, in parse
    lineno)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 776, in interpreted_or_phrase_ref
    lineno)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 856, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)

  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admindocs/utils.py", line 97, in default_reference_role
    context = inliner.document.settings.default_reference_context

AttributeError: 'Values' object has no attribute 'default_reference_context'


<WSGIRequest
path:/admin/pages/page/57/,
GET:<QueryDict: {}>,
POST:{'_save': 'Save',
 'content': ...snip..,
 'content_markup_type': 'restructuredtext',
 'csrfmiddlewaretoken': [redacted[,
 'description': '',
 'image_set-0-id': '',
 'image_set-0-image': '',
 'image_set-0-page': '57',
 'image_set-INITIAL_FORMS': '0',
 'image_set-MAX_NUM_FORMS': '1000',
 'image_set-TOTAL_FORMS': '1',
 'image_set-__prefix__-id': '',
 'image_set-__prefix__-image': '',
 'image_set-__prefix__-page': '57',
 'is_published': 'on',
 'keywords': '',
 'path': 'community/jobs',
 'template_name': '',
 'title': 'Python Job Board'},
COOKIES:{'csrftoken': '8V8tVMENYG0wRF3TGF3PvmjfsSjTUEiy',
 'sessionid': 'q5kixj4mlerjl0ewyf3xwe68bqv9vfzd'},
META:{'CONTENT_LENGTH': '211305',
 'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------264492417326002',
 'CSRF_COOKIE': '8V8tVMENYG0wRF3TGF3PvmjfsSjTUEiy',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'csrftoken=8V8tVMENYG0wRF3TGF3PvmjfsSjTUEiy; sessionid=q5kixj4mlerjl0ewyf3xwe68bqv9vfzd',
 'HTTP_DNT': '1',
 'HTTP_FASTLY_CLIENT_IP': '95.223.110.34',
 'HTTP_FASTLY_FF': 'cache-fra1228-FRA',
 'HTTP_FASTLY_SSL': '1',
 'HTTP_FASTLY_TEMP_XFF': '95.223.110.34, 95.223.110.34',
 'HTTP_HOST': 'www.python.org',
 'HTTP_REFERER': 'https://www.python.org/admin/pages/page/57/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0',
 'HTTP_X_FORWARDED_FOR': [redacted],
 'HTTP_X_FORWARDED_HOST': 'www.python.org',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_FORWARDED_SERVER': '185-31-17-143.hosts.fastly.net',
 'HTTP_X_REAL_IP': [redacted],
 'HTTP_X_VARNISH': '2833515300',
 'PATH_INFO': '/admin/pages/page/57/',
 'QUERY_STRING': '',
 'RAW_URI': '/admin/pages/page/57/',
 'REMOTE_ADDR': [redacted],
 'REMOTE_PORT': [redacted],
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'www.python.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/18.0',
 'gunicorn.socket': <socket.socket object, fd=10, family=2, type=1, proto=0>,
 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='ANSI_X3.4-1968'>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x7f1753cd0e50>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by malemburg** [comment]
Could the admindocs app be the cause ?

```
  File "/srv/redesign.python.org/shared/env/lib/python3.3/site-packages/django/contrib/admindocs/utils.py", line 97, in default_reference_role
    context = inliner.document.settings.default_reference_context

AttributeError: 'Values' object has no attribute 'default_reference_context'
```

**Comment by benjaminp** [comment]
https://code.djangoproject.com/ticket/6681 I suppose.

**Comment by malemburg** [comment]
The traceback in that ticket sure looks similar :-)

This is the patch they applied: https://github.com/django/django/commit/bcd4c3f27d5bcf701337ac7c74c042d90792bdc3

Could we get the same patch applied as temporary fix ?

If not, I guess we could try to just add the

```
.. default-role:: cmsreference
```

to the page content.

**Comment by malemburg** [comment]
Just tried this: doesn't work. I still get the error.

**Comment by malemburg** [comment]
This did the trick, thanks. I have successfully edited the jobs board page.
