### ISSUE TITLE
testFAILED (errors=3, skipped=1)

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#400]
```
(ENV)vagrant@precise64:~/pythondotorg$ coverage run manage.py test
Creating test database for alias 'default'...
...................s........................................................................................................EEE........
======================================================================
ERROR: pages.tests.test_models (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/usr/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: pages.tests.test_models
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/vagrant/pythondotorg/pages/tests/__init__.py", line 1, in <module>
    from .test_models import *
  File "/home/vagrant/pythondotorg/pages/tests/test_models.py", line 1, in <module>
    import ddt
ImportError: No module named 'ddt'


======================================================================
ERROR: pages.tests.test_views (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/usr/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: pages.tests.test_views
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/vagrant/pythondotorg/pages/tests/__init__.py", line 1, in <module>
    from .test_models import *
  File "/home/vagrant/pythondotorg/pages/tests/test_models.py", line 1, in <module>
    import ddt
ImportError: No module named 'ddt'


======================================================================
ERROR: pages.tests.test_parser (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/usr/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: pages.tests.test_parser
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/home/vagrant/pythondotorg/pages/tests/__init__.py", line 1, in <module>
    from .test_models import *
  File "/home/vagrant/pythondotorg/pages/tests/test_models.py", line 1, in <module>
    import ddt
ImportError: No module named 'ddt'


----------------------------------------------------------------------
Ran 135 tests in 48.846s

FAILED (errors=3, skipped=1)
Destroying test database for alias 'default'...
```

**Comment by CarlFK** [comment]
I am guessing it is as simple as adding ddt to requirements.txt

```
(ENV)vagrant@precise64:~/pythondotorg$ pip install ddt
...
Successfully installed ddt
Cleaning up...
(ENV)vagrant@precise64:~/pythondotorg$ coverage run manage.py test
Creating test database for alias 'default'...
...................s..................................................................................................................................
----------------------------------------------------------------------
Ran 150 tests in 52.648s

OK (skipped=1)
Destroying test database for alias 'default'...
```

**Comment by fcurella** [comment]
FWIW, `ddt` is already in `dev-requirements.txt`

**Comment by frankwiles** [comment]
Both coverage and ddt are in dev-requirements so should be fine.
