### ISSUE TITLE
load_dev_fixtures raises IntegrityError

### ISSUE THREAD

**Issue by berkerpeksag** [python/pythondotorg#726]
With a fresh database:

``` shell
$ export DATABASE_URL=postgres:///pydotorgtest
$ ./manage.py migrate
$ ./manage.py load_dev_fixtures
...
...
django.db.utils.IntegrityError: Problem installing fixture '/tmp/dev-fixtures.json.gz': Could not load jobs.Job(pk=1): null value in column "job_title" violates not-null constraint
```

See pk=1 job entry on admin interface: https://www.python.org/admin/jobs/job/1/

I think the problem is old job entries. Some of the entries have empty "job_title" field. Dumping entries from 2015 (or deleting incomplete and useless entries) would solve the problem.

**Comment by frankwiles** [comment]
Fixed the data in prod to get around this, which bubbled up more integrity issues with the data loading it in fresh which I'm working on resolving now.

**Comment by berkerpeksag** [comment]
Thanks @frankwiles! Now I'm getting the following exception:

```
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/models/fields/related.py", line 555, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Release' object has no attribute '_release_page_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/berker/projects/pythondotorg/cms/management/commands/load_dev_fixtures.py", line 40, in handle_noargs
    call_command('loaddata', '/tmp/dev-fixtures.json')
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/berker/projects/pythondotorg/downloads/models.py", line 220, in purge_fastly_download_pages
    purge_url(instance.get_absolute_url())
  File "/home/berker/projects/pythondotorg/downloads/models.py", line 94, in get_absolute_url
    if not self.content.raw and self.release_page:
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
pages.models.DoesNotExist: Problem installing fixture '/tmp/dev-fixtures.json.gz': Page matching query does not exist.
```

**Comment by mlhamel** [comment]
i've also replace all empty value for job_title for a random and got the same error...

**Comment by berkerpeksag** [comment]
https://github.com/python/pythondotorg/commit/c3e164e9c44cd684243f0b0fb69fecf6215774a2 fixed most of the issues for me, thanks! Here is the current traceback with a fresh database:

```
$ ./manage.py load_dev_fixtures
/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/contrib/comments/__init__.py:13: RemovedInDjango18Warning: django.contrib.comments is deprecated and will be removed before Django 1.8.
  warnings.warn("django.contrib.comments is deprecated and will be removed before Django 1.8.", RemovedInDjango18Warning)

You have requested to load the python.org development fixtures.
This will IRREVERSIBLY DESTROY all data currently in your local database.
Are you sure you want to do this?

    Type 'y' or 'yes' to continue, 'n' or 'no' to cancel:  y

Beginning download, note this can take a couple of minutes...
Download complete, loading fixtures
Traceback (most recent call last):
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.IntegrityError: insert or update on table "users_user_groups" violates foreign key constraint "users_user_groups_group_id_cab2f5f97af9816_fk_auth_group_id"
DETAIL:  Key (group_id)=(1) is not present in table "auth_group".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/berker/projects/pythondotorg/cms/management/commands/load_dev_fixtures.py", line 46, in handle_noargs
    call_command('loaddata', '/tmp/dev-fixtures.json')
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/core/management/commands/loaddata.py", line 97, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 205, in check_constraints
    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/berker/projects/pythondotorg/venv/lib/python3.3/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "users_user_groups" violates foreign key constraint "users_user_groups_group_id_cab2f5f97af9816_fk_auth_group_id"
DETAIL:  Key (group_id)=(1) is not present in table "auth_group".
```

The commands I used:

``` shell
$ export DATABASE_URL=postgres:///pydotorgtest2
$ createdb pydotorgtest2
$ ./manage.py migrate
$ ./manage.py load_dev_fixtures
```

(Sorry, I won't have too much time to debug further this week, but hopefully I'll have more time to take a look at this in this weekend.)

**Comment by mlhamel** [comment]
It totally work for me with latest changes made by @frankwiles at c3e164e9c44cd684243f0b0fb69fecf6215774a2 :) thanks !

**Comment by berkerpeksag** [comment]
With a fresh git clone and database, I'm still getting the same traceback. @mlhamel did you run the commands I posted above? What's your PostgreSQL version?

**Comment by berkerpeksag** [comment]
With the following inline patch, it worked for me(please ignore the `verbosity=2` part):

``` diff
diff --git a/cms/management/commands/load_dev_fixtures.py b/cms/management/commands/load_dev_fixtures.py
index 10d6832..1c9881e 100644
--- a/cms/management/commands/load_dev_fixtures.py
+++ b/cms/management/commands/load_dev_fixtures.py
@@ -43,5 +43,5 @@ Are you sure you want to do this?
                     f.flush()

             self.stdout.write("Download complete, loading fixtures")
-            call_command('loaddata', '/tmp/dev-fixtures.json')
+            call_command('loaddata', '/tmp/dev-fixtures.json.gz', verbosity=2)
             self.stdout.write("END: Fixtures loaded")
```

```
$ ./manage.py load_dev_fixtures
[...]
Beginning download, note this can take a couple of minutes...
Download complete, loading fixtures
Loading '/tmp/dev-fixtures' fixtures...
Checking '/tmp' for fixtures...
Installing json fixture 'dev-fixtures' from '/tmp'.
Resetting sequences
Installed 46371 object(s) from 1 fixture(s)
END: Fixtures loaded
```

@frankwiles do you want me to commit this? Thank you by the way, development experience is much better now :)

**Comment by mlhamel** [comment]
@berkerpeksag I haven't tried with PostgreSQL but on SQLite which would explain why it was working only for me

**Comment by berkerpeksag** [comment]
Just tried this again and couldn't reproduce the problem I had earlier. Closing as "fixed".
