### ISSUE TITLE
pip doesn't work

### ISSUE THREAD

**Issue by AZR81** [python/pythondotorg#861]
My pip can't download or upgrade anything
I use python 3.5 (win 32) and my pip version is 7.1.2.
The error message is this:

Exception:
Traceback (most recent call last):
File "c:\program files\python 3.5\lib\site-packages\pip\basecommand.py", line 211, in main
status = self.run(options, args)
File "c:\program files\python 3.5\lib\site-packages\pip\commands\install.py", line 311, in run
root=options.root_path,
File "c:\program files\python 3.5\lib\site-packages\pip\req\req_set.py", line 646, in install
**kwargs
File "c:\program files\python 3.5\lib\site-packages\pip\req\req_install.py", line 803, in install
self.move_wheel_files(self.source_dir, root=root)
File "c:\program files\python 3.5\lib\site-packages\pip\req\req_install.py", line 998, in move_wheel_files
insolated=self.isolated,
File "c:\program files\python 3.5\lib\site-packages\pip\wheel.py", line 339, in move_wheel_files
clobber(source, lib_dir, True)
File "c:\program files\python 3.5\lib\site-packages\pip\wheel.py", line 317, in clobber
shutil.copyfile(srcfile, destfile)
File "c:\program files\python 3.5\lib\shutil.py", line 115, in copyfile
with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'c:\program files\python 3.5\Lib\site-packages\PyWin32.chm'

What do I have to do?

**Comment by lac22** [comment]
Hello there.  I am sorry you are having problems.  Unfortunately, the pydotorg tracker is for
problems with the python.org website, not python problems in general.  Please subscribe
to the general python questions mailing list: https://mail.python.org/mailman/listinfo/python-list
and ask this question there.

**Comment by AZR81** [comment]
The problem fixed.
That was only about User Account Control
