### ISSUE TITLE
CREATE DATABASE not documented 

### ISSUE THREAD

**Issue by CarlFK** [python/pythondotorg#890]
https://pythondotorg.readthedocs.org/install.html#manual-setup

To load all fixture files
$ ./manage.py load_dev_fixtures:

```
django.db.utils.DataError: Problem installing fixture '/tmp/dev-fixtures.json.gz': Could not load users.User(pk=6493): value too long for type character varying(30)
```

```
(pdo) carl@twist:~/src/pythondotorg$ ./manage.py load_dev_fixtures

/home/carl/temp/pdo/lib/python3.4/site-packages/django/contrib/comments/__init__.py:13: RemovedInDjango18Warning: django.contrib.comments is deprecated and will be removed before Django 1.8.
  warnings.warn("django.contrib.comments is deprecated and will be removed before Django 1.8.", RemovedInDjango18Warning)

/home/carl/temp/pdo/lib/python3.4/site-packages/tastypie/resources.py:2210: RemovedInDjango18Warning: commit_on_success is deprecated in favor of atomic.
  @transaction.commit_on_success()

You have requested to load the python.org development fixtures.
This will IRREVERSIBLY DESTROY all data currently in your local database.
Are you sure you want to do this?

    Type 'y' or 'yes' to continue, 'n' or 'no' to cancel:  y

Beginning download, note this can take a couple of minutes...
Download complete, loading fixtures
Traceback (most recent call last):
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(30)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/carl/src/pythondotorg/cms/management/commands/load_dev_fixtures.py", line 46, in handle_noargs
    call_command('loaddata', '/tmp/dev-fixtures.json')
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/base.py", line 679, in _save_table
    forced_update)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/base.py", line 723, in _do_update
    return filtered._update(values) > 0
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1005, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/carl/temp/pdo/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: Problem installing fixture '/tmp/dev-fixtures.json.gz': Could not load users.User(pk=6493): value too long for type character varying(30)
```

**Comment by CarlFK** [comment]
I am getting this error because I did not create the database correctly.
https://pythondotorg.readthedocs.org/install.html#manual-setup says:
`pythondotorg will look for a PostgreSQL database named pythondotorg`

the create command needs encoding='UTF-8' and maybe some other parameters specified in:

https://github.com/python/pythondotorg/blob/master/provisioning/pythondotorg.yml#L58-L62

```
    postgresql_db: name={{ database.name }}
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     state=present
```

Anyone know what the full command is?

**Comment by berkerpeksag** [comment]
``` sh
$ createdb pythondotorg -E utf-8
```

We should probably add the command above to the installation document.

**Comment by berkerpeksag** [comment]
Or, to be more specific:

```
$ createdb pythondotorg -E utf-8 --locale=en_US.UTF-8
```
